plugin_format_version: 2
name: admin-ui-group
namespace: official
version: 1.1.1-4
author: Wazo Team
display_name: Groups
min_wazo_version: 18.02
tags:
  - users
homepage: https://github.com/wazo-pbx/wazo-admin-ui-group
depends:
  - name: admin-ui-context
    namespace: official
    version: ">= 1.1.1-2"
  - name: admin-ui-extension
    namespace: official
    version: ">= 1.2.0-2"
  - name: admin-ui-schedule
    namespace: official
    version: ">= 0.0.1-2"
